### ISSUE TITLE
Redo bad example at last line

### ISSUE THREAD

**Issue by ev1stensberg** [ev1stensberg/proposal-reflect-or#1]
I know that the last example is a bit odd, so please drop a PR if you got something better in mind

**Comment by bergus** [comment]
The most obvious reason why it is a bad example is because of the expression `typeof obj === undefined` which can never be true.
And even in case you meant
```js
var wrapper = obj || safeValue;

if(typeof obj === "undefined" && typeof safeValue === "undefined") {
 wrapper == undefined;
}
```
I cannot see why that if statement would be necessary at all.

**Comment by ev1stensberg** [comment]
Feel free to set up a PR regarding this! The example was to try show that we preserve context for wrapper instead of having to check the underlying values, though this was not required. I'll most likely change this later once I've got the time, but if you want to redo this, go ahead!

**Comment by bergus** [comment]
> … preserve context for wrapper …

What?
No, I'm not going to make a pull request until I understand what this line is all about - afaics it should be completely omitted.

**Comment by bergus** [comment]
Ah, I just saw that you've already replaced it by an `!isValidObject` call in 24b0bb571e9c779af2df02ba92664109998c8f1d. Now, does that function do?

**Comment by ev1stensberg** [comment]
It checks if it is an valid object, [from lodash](https://lodash.com/docs#isObject). Was supposed to be `isPlainObject` , but I think that it shows more with valid than plain in order for people to get the use case.

**Comment by bergus** [comment]
> from lodash

Ah. You really should've stated that. It's not obvious. Btw, in native terms, you could use `Object(wrapper) === wrapper`.

>  I think that it shows more with valid than plain in order for people to get the use case.

No. "Valid" could mean anything.

In this case, the proposed `safeValue = "Hi! This is the fallback value"` would be invalid for example, which doesn't make sense to me, further obscuring the use case.

Btw, instead of `wrapper == undefined` you probably meant an assignment.

**Comment by ev1stensberg** [comment]
I did, changed it up now. If safeValue is false, then wrapper == obj would return true.
